---
- name: Deploy Caddy using Docker
  hosts: all
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - cron
        state: present

    - name: Clone the dc-reverse-proxy-config repository
      git:
        repo: https://github.com/ozeliurs/dc-reverse-proxy-config.git
        dest: /opt/dc-reverse-proxy-config
        update: yes

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh -
      args:
        creates: /usr/bin/docker

    - name: Copy .env file to the target server
      copy:
        src: ./.env
        dest: /opt/dc-reverse-proxy-config/caddy/.env
        mode: "0644"

    - name: Start Docker Compose
      shell: docker compose -f /opt/dc-reverse-proxy-config/caddy/docker-compose.yaml up -d

    - name: Create update script
      copy:
        dest: /usr/local/bin/update_caddy.sh
        content: |
          #!/bin/bash
          cd /opt/dc-reverse-proxy-config
          git remote update
          if ! git status -uno | grep -q 'Your branch is up to date'; then
            git pull
            cd caddy
            docker compose down
            docker compose up -d
          fi
        mode: "0755"

    - name: Add cron job to check for updates every minute
      cron:
        name: "Check for updates and restart Caddy if necessary"
        minute: "*"
        hour: "*"
        job: "/usr/local/bin/update_caddy.sh"
